"""empty message

Revision ID: 9d66c7d65656
Revises: 
Create Date: 2026-02-11 18:09:46.033549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9d66c7d65656'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objeto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archivos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proveedor_ruc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proceso')
    # ### end Alembic commands ###
